name: Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (e.g., dev, prod)'
        required: true
        default: 'dev'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5  # or your version

      - name: Terraform Init
        working-directory: terraform_asg
        run: terraform init -backend-config="key=ec2/${{ github.event.inputs.environment }}/terraform.tfstate"

      - name: Terraform Validate
        working-directory: terraform_asg
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform_asg
        run: terraform plan -var="env=${{ github.event.inputs.environment }}" -var-file="terraform.tfvars"

      # Optional: Apply step (manual approval recommended)
      - name: Terraform Apply
        if: github.event.inputs.environment == 'prod'
        working-directory: terraform_asg
        run: terraform apply -auto-approve -var="env=${{ github.event.inputs.environment }}" -var-file="terraform.tfvars"
