name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (e.g., dev, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

      module:
        description: "Select which module to deploy"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - ec2
          - launch_template
          - asg
          - alb

      action:
        description: "Select Terraform Action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform_asg
        run: terraform init -backend-config="key=${{ github.event.inputs.module }}/${{ github.event.inputs.environment }}/terraform.tfstate"

      - name: Terraform Validate
        working-directory: terraform_asg
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        working-directory: terraform_asg
        run: |
          if [ "${{ github.event.inputs.module }}" = "all" ]; then
            terraform plan -var="env=${{ github.event.inputs.environment }}" -var-file="terraform.tfvars"
          else
            terraform plan \
              -target="module.${{ github.event.inputs.module }}" \
              -var="env=${{ github.event.inputs.environment }}" \
              -var-file="terraform.tfvars"
          fi

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        working-directory: terraform_asg
        run: |
          if [ "${{ github.event.inputs.module }}" = "all" ]; then
            terraform apply -auto-approve -var="env=${{ github.event.inputs.environment }}" -var-file="terraform.tfvars"
          else
            terraform apply \
              -target="module.${{ github.event.inputs.module }}" \
              -auto-approve \
              -var="env=${{ github.event.inputs.environment }}" \
              -var-file="terraform.tfvars"
          fi
